version = 0.1
[default.deploy.parameters]
stack_name = "csv-importer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12s1paybggis7"
s3_prefix = "csv-importer"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ProductBucketName=\"btbvm001-product-v1\""
image_repositories = []
