AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: patterns-ddb-importer-v1

Parameters:
  ProductBucketName:
    Type: String
    Default: "btbvm001-product-v1"

Resources:
  ProductS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ProductBucketName

  ProductTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: sku
          AttributeType: S
      KeySchema:
        - AttributeName: sku
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ImportProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: importFunction/
      Handler: app.handler
      Runtime: nodejs18.x
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          PRODUCT_TABLE: !Ref ProductTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductTable
        - S3CrudPolicy:
            BucketName: !Ref ProductBucketName
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref ProductS3Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: ".csv"
