version = 0.1
[default.deploy.parameters]
stack_name = "csv-importer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12s1paybggis7"
s3_prefix = "csv-importer"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "ProductFunctionName=\"btbvm001-product-processor\" StockFunctionName=\"btbvm001-stock-processor\" ProductBucketName=\"btbvm001-product-v1\" StockBucketName=\"btbvm001-stock-v1\" ProductTableName=\"btbvm001-product-table\" StockTableName=\"btbvm001-stock-table\" APIName=\"btbvm001-appsync\""
image_repositories = []
